(defun main()
	(setq x1 (read))
	(setq y1 (read))
	(setq z1 (read))
	(setq x2 (read))
	(setq y2 (read))
	(setq z2 (read))
	(setq delta_x ( (lambda (x1 x2) (expt (- x1 x2) 2) ) x1 x2 ))
	(setq delta_y ( (lambda (y1 y2) (expt (- y1 y2) 2) ) y1 y2 ))
	(setq delta_z ( (lambda (z1 z2) (expt (- z1 z2) 2) ) z1 z2 ))
	(setq distancia ( (lambda (dx dy dz) 
		(sqrt (+ dx dy dz))
		) delta_x delta_y delta_z ) 
	)
	(write-line (write-to-string distancia))
	
)

(main)