(defun bhaskara(a b c)
	(setq bquadrado (* b b))
	(setq 4AC (* 4 a c))
	(setq delta (- bquadrado 4AC))
	(setq raizDelta (sqrt delta))
	(setq raiz1 (/ (+ (- 0 b) raizDelta ) (* a 2.0) ) )
	(setq raiz2 (/ (- (- 0 b) raizDelta ) (* a 2.0) ) )
	(setq raiz1Str (write-to-string raiz1))
	(setq raiz2Str (write-to-string raiz2))
	(setq raizes (concatenate 'string "x1: " raiz1Str " x2: " raiz2Str) )
	(write raizes)
)

(defun main()
	(setq a (read))
	(setq b (read))
	(setq c (read))
	(bhaskara a b c)
)

(main)