(defun distancia(x1 y1 z1 x2 y2 z2)
	(setq deltaX (- x1 x2))
	(setq deltaY (- y1 y2))
	(setq deltaZ (- z1 z2))
	(setq deltaXQ (* deltaX deltaX))
	(setq deltaYQ (* deltaY deltaY))
	(setq deltaZQ (* deltaZ deltaZ))
	(sqrt (+ deltaXQ deltaYQ deltaZQ))
)

(defun main()
	(write-line "Coordenada x1:")
	(setq x1 (read))
	(write-line "Coordenada y1:")
	(setq y1 (read))
	(write-line "Coordenada z1:")
	(setq z1 (read))
	(write-line "Coordenada x2:")
	(setq x2 (read))
	(write-line "Coordenada y2:")
	(setq y2 (read))
	(write-line "Coordenada z2:")
	(setq z2 (read))
	(write-line (write-to-string(distancia x1 y1 z1 x2 y2 z2)))
)

(main)